version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '02:00'
      timezone: "Africa/Nairobi"
    open-pull-requests-limit: 10
    target-branch: main
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: weekly
      time: '02:00'
      timezone: "Africa/Nairobi"
    open-pull-requests-limit: 10
    target-branch: main
